// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://phtsroxtfnaoseeynofx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBodHNyb3h0Zm5hb3NlZXlub2Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5Mjg5OTYsImV4cCI6MjA3MzUwNDk5Nn0.xZRdcU0LpgX0nN5pN5ciy5KF86LVTWU_nmU2XnTvZlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});